# repo-root/render.yaml
services:
  - type: web
    name: todo-backend
    rootDir: todo-backend
    runtime: docker 
# Docker使わない場合
#    buildCommand: ./gradlew clean build -x test
#    startCommand: java -jar build/libs/*-SNAPSHOT.jar
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString

databases:
  - name: todo-db
    databaseName: todo
    plan: free
