# repo-root/.github/workflows/backend-ci.yml
name: backend-ci
on:
  push:
    paths:
      - 'todo-backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'todo-backend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      # テスト込みビルド（-x test を外す）
      - name: Build (with tests)
        run: ./gradlew clean build

      # テスト成功 & main への push のときだけ Render を起動
      - name: Trigger Render Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
        run: curl -sSf -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
